apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flaskdemo
  name: flaskdemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskdemo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flaskdemo
    spec:
      containers:
<<<<<<< HEAD
      - image: vinaay/argocd:6
=======
      - image: raj80dockerid/test:8
>>>>>>> 2b08ce9b11e2a88f6d749914e197b144a7c0274e
        name: flaskdemo
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 81
    targetPort: 5000
  selector:
    app: flaskdemo
